customers/urls.py
from django.urls import path

from . import views

app_name = 'customers'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

customers/models.py
from django.db import models

class Customer(models.Model):
    name = models.TextField()
    street_address = models.TextField(null=True)
    city = models.TextField(null=True)
    state = models.TextField(null=True)
    postal_code = models.TextField(null=True)
    country_code = models.TextField(null=True)
    phone_number = models.TextField(null=True)
    website_url = models.URLField(null=True)
    created_on = models.DateField(auto_now_add=True)

class Contact(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    name = models.TextField()
    email = models.EmailField()
    phone_number = models.TextField(null=True)

documents/models.py
from django.db import models

class Document(models.Model):
    name = models.TextField()
    url = models.URLField()
    created_on = models.DateField(auto_now_add=True)

organizations/models.py
from django.db import models
from django_tenants.models import TenantMixin, DomainMixin


class Organization(TenantMixin):
    name = models.TextField()
    logo_url = models.TextField(null=True)
    street_address = models.TextField(null=True)
    city = models.TextField(null=True)
    state = models.TextField(null=True)
    postal_code = models.TextField(null=True)
    country_code = models.TextField(null=True)
    phone_number = models.TextField(null=True)
    website_url = models.TextField(null=True)
    employees = models.IntegerField(null=True)
    founded_at = models.DateField(null=True)
    annual_revenue_range = models.TextField(null=True)

    created_on = models.DateField(auto_now_add=True)

    # default true, schema will be automatically created and synced when it is saved
    auto_create_schema = True


class Domain(DomainMixin):
    pass

theme/models.py
from django.db import models

# Create your models here.

customers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from .models import Customer

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'customers/index.html'
    context_object_name = 'customer_list'

    def get_queryset(self):
        """Return the last five published customers."""
        return Customer.objects.order_by('-name')[:5]


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Customer
    template_name = 'customers/detail.html'

documents/views.py
from django.shortcuts import render

# Create your views here.

organizations/views.py
from django.shortcuts import render

# Create your views here.

theme/views.py
from django.shortcuts import render

# Create your views here.

customers/templates/customers/detail.html
<h1>{{ customer.name }}</h1>

customers/templates/customers/index.html
{% extends "theme/index.html" %}

{% block title %}Customer List{% endblock %}

{% block content %}
    {% if customer_list %}
        <ul>
            {% for customer in customer_list %}
                <li>
                    <a href="{% url 'customers:detail' customer.id %}">{{ customer.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No customers are available.</p>
    {% endif %}
{% endblock %}

templates/django/forms/attrs.html
{% for name, value in attrs.items %}{% if value is not False %} {{ name }}{% if value is not True %}="{{ value|stringformat:'s' }}"{% endif %}{% endif %}{% endfor %}

templates/django/forms/default.html
{% if errors %}
  {{ errors }}
  {% if not fields %}
    {% for field in hidden_fields %}{{ field }}{% endfor %}
  {% endif %}
{% endif %}

{% for field, errors in fields %}
  <tr{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    <th>{% if field.label %}{{ field.label_tag }}{% endif %}</th>
    <td>
      {{ errors }}
      {{ field }}
      {% if field.help_text %}
        <br>
        <span class="helptext">{{ field.help_text }}</span>
      {% endif %}
      {% if forloop.last %}
        {% for field in hidden_fields %}{{ field }}{% endfor %}
      {% endif %}
    </td>
  </tr>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}

templates/django/forms/formsets/default.html
{{ formset.management_form }}{% for form in formset %}{{ form }}{% endfor %}

templates/django/forms/formsets/p.html
{{ formset.management_form }}{% for form in formset %}{{ form.as_p }}{% endfor %}

templates/django/forms/formsets/table.html
{{ formset.management_form }}{% for form in formset %}{{ form.as_table }}{% endfor %}

templates/django/forms/formsets/ul.html
{{ formset.management_form }}{% for form in formset %}{{ form.as_ul }}{% endfor %}

templates/django/forms/label.html
{% if use_tag %}<label{% include 'django/forms/attrs.html' %}>{{ label }}</label>{% else %}{{ label }}{% endif %}

templates/django/forms/p.html
{{ errors }}
{% if errors and not fields %}
  <p>{% for field in hidden_fields %}{{ field }}{% endfor %}</p>
{% endif %}
{% for field, errors in fields %}
  {{ errors }}
  <p{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    {% if field.label %}{{ field.label_tag }}{% endif %}
    {{ field }}
    {% if field.help_text %}
      <span class="helptext">{{ field.help_text }}</span>
    {% endif %}
    {% if forloop.last %}
      {% for field in hidden_fields %}{{ field }}{% endfor %}
    {% endif %}
  </p>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}

templates/django/forms/table.html
{% if errors %}
  <tr>
    <td colspan="2">
      {{ errors }}
      {% if not fields %}
        {% for field in hidden_fields %}{{ field }}{% endfor %}
      {% endif %}
    </td>
  </tr>
{% endif %}
{% for field, errors in fields %}
  <tr{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    <th>{% if field.label %}{{ field.label_tag }}{% endif %}</th>
    <td>
      {{ errors }}
      {{ field }}
      {% if field.help_text %}
        <br>
        <span class="helptext">{{ field.help_text }}</span>
      {% endif %}
      {% if forloop.last %}
        {% for field in hidden_fields %}{{ field }}{% endfor %}
      {% endif %}
    </td>
  </tr>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}

templates/django/forms/ul.html
{% if errors %}
  <li>
    {{ errors }}
  {% if not fields %}
    {% for field in hidden_fields %}{{ field }}{% endfor %}
  {% endif %}
  </li>
{% endif %}
{% for field, errors in fields %}
  <li{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    {{ errors }}
    {% if field.label %}{{ field.label_tag }}{% endif %}
    {{ field }}
    {% if field.help_text %}
      <span class="helptext">{{ field.help_text }}</span>
    {% endif %}
    {% if forloop.last %}
      {% for field in hidden_fields %}{{ field }}{% endfor %}
    {% endif %}
  </li>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}

templates/django/forms/widgets/checkbox.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/checkbox_select.html
{% include "django/forms/widgets/multiple_input.html" %}

templates/django/forms/widgets/clearable_file_input.html
{% if widget.is_initial %}{{ widget.initial_text }}: <a href="{{ widget.value.url }}">{{ widget.value }}</a>{% if not widget.required %}
<input type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}"{% if widget.attrs.disabled %} disabled{% endif %}>
<label for="{{ widget.checkbox_id }}">{{ widget.clear_checkbox_label }}</label>{% endif %}<br>
{{ widget.input_text }}:{% endif %}
<input type="{{ widget.type }}" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>

templates/django/forms/widgets/date.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/datetime.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/input_option.html
{% if widget.wrap_label %}<label{% if widget.attrs.id %} for="{{ widget.attrs.id }}"{% endif %}>{% endif %}{% include "django/forms/widgets/input.html" %}{% if widget.wrap_label %} {{ widget.label }}</label>{% endif %}

templates/django/forms/widgets/password.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/radio_option.html
{% include "django/forms/widgets/input_option.html" %}

templates/django/forms/widgets/select.html
<select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
  <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
  {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
  </optgroup>{% endif %}{% endfor %}
</select>

templates/django/forms/widgets/select_date.html
{% include 'django/forms/widgets/multiwidget.html' %}

templates/django/forms/widgets/select_option.html
<option value="{{ widget.value|stringformat:'s' }}"{% include "django/forms/widgets/attrs.html" %}>{{ widget.label }}</option>

templates/django/forms/widgets/splithiddendatetime.html
{% include 'django/forms/widgets/multiwidget.html' %}

templates/django/forms/widgets/text.html
{% include "django/forms/widgets/input.html" %}

templates/django/forms/widgets/url.html
{% include "django/forms/widgets/input.html" %}

theme/templates/theme/index.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {% bootstrap_css %}
        <title>{% block title %}Project M{% endblock %}</title>
    </head>

    <body class="h-full overflow-hidden">
        {% block content %}Project M{% endblock %} {% bootstrap_javascript %}
    </body>
</html>

theme/templates/theme/navbar.html
<nav aria-label="Sidebar" class="mt-5">
    <div class="px-2 space-y-1">
        <!-- Current: "bg-gray-100 text-gray-900", Default: "text-gray-600 hover:bg-gray-50 hover:text-gray-900" -->
        <a
            href="{% url 'customers:index' %}"
            class="
            bg-gray-100
            text-gray-900
            group
            flex
            items-center
            px-2
            py-2
            text-base
            font-medium
            rounded-md
            "
        >
            <!--
          Heroicon name: outline/home

          Current: "text-gray-500", Default: "text-gray-400 group-hover:text-gray-500"
        -->
            <svg
                class="text-gray-500 mr-4 h-6 w-6"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
            >
                <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
                />
            </svg>
            Dashboard
        </a>

        <a
            href="{% url 'customers:index' %}"
            class="
            text-gray-600
            hover:bg-gray-50 hover:text-gray-900
            group
            flex
            items-center
            px-2
            py-2
            text-base
            font-medium
            rounded-md
            "
        >
            <!-- Heroicon name: outline/calendar -->
            <svg
                class="text-gray-400 group-hover:text-gray-500 mr-4 h-6 w-6"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
            >
                <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                />
            </svg>
            Calendar
        </a>

        <a
            href="{% url 'customers:index' %}"
            class="
            text-gray-600
            hover:bg-gray-50 hover:text-gray-900
            group
            flex
            items-center
            px-2
            py-2
            text-base
            font-medium
            rounded-md
            "
        >
            <!-- Heroicon name: outline/user-group -->
            <svg
                class="text-gray-400 group-hover:text-gray-500 mr-4 h-6 w-6"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
            >
                <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"
                />
            </svg>
            Teams
        </a>

        <a
            href="{% url 'customers:index' %}"
            class="
            text-gray-600
            hover:bg-gray-50 hover:text-gray-900
            group
            flex
            items-center
            px-2
            py-2
            text-base
            font-medium
            rounded-md
            "
        >
            <!-- Heroicon name: outline/search-circle -->
            <svg
                class="text-gray-400 group-hover:text-gray-500 mr-4 h-6 w-6"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
            >
                <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M8 16l2.879-2.879m0 0a3 3 0 104.243-4.242 3 3 0 00-4.243 4.242zM21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
            </svg>
            Directory
        </a>

        <a
            href="{% url 'customers:index' %}"
            class="
            text-gray-600
            hover:bg-gray-50 hover:text-gray-900
            group
            flex
            items-center
            px-2
            py-2
            text-base
            font-medium
            rounded-md
            "
        >
            <!-- Heroicon name: outline/speakerphone -->
            <svg
                class="text-gray-400 group-hover:text-gray-500 mr-4 h-6 w-6"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
            >
                <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z"
                />
            </svg>
            Announcements
        </a>

        <a
            href="{% url 'customers:index' %}"
            class="
            text-gray-600
            hover:bg-gray-50 hover:text-gray-900
            group
            flex
            items-center
            px-2
            py-2
            text-base
            font-medium
            rounded-md
            "
        >
            <!-- Heroicon name: outline/map -->
            <svg
                class="text-gray-400 group-hover:text-gray-500 mr-4 h-6 w-6"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-hidden="true"
            >
                <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7"
                />
            </svg>
            Office Map
        </a>
    </div>
</nav>